# Application Configuration
spring:
  application:
    name: user-management

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/user_management
    username: app_user
    password: pa55P0rt
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      port: 6379
      host: "localhost"

  # Liquibase Configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

# Keycloak Configuration
keycloak:
  auth-server-url: https://dfs-auth-dev.qena.dev
  realm: user-management
  resource: webClient
  public-client: false
  bearer-only: true
  admin-client:
    id: webClient
    secret: 38cGbFmarnZjWFo8Za3dUPGt2qdscGpq

# JWT Configuration
spring.security.oauth2.resourceserver.jwt:
  issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
  jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs

# Caching Configuration
spring.cache:
  type: redis

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    org.springframework.security: DEBUG
    org.keycloak: INFO
    com.example.usermanagement: DEBUG
    com.example.usermanagement.security: TRACE
